Custom completion, stop using mcedit in mc, install script fixes.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,15 +1,21 @@
 #!/bin/bash
-# links list file
-links=$HOME/dotfiles/install.list
-# check list file
-[ ! -f $links ] && echo "Links list file not found. Exiting." && exit 1
-# read files
-while read symlink; do
-  # check if file/symlink exist 
-  [ -f $HOME/$symlink ] && echo -e "File exists:\t$HOME/$symlink" && continue
-  # check if destination exists in dotfiles
-  [ ! -f $HOME/dotfiles/${symlink:1} ] && echo -e "Source missing:\t$HOME/dotfiles/${symlink:1}" && continue
-  # symlink
-  echo -e "Linking:\t$HOME/dotfiles/${symlink:1} -> $HOME/$symlink"
-  ln -s $HOME/dotfiles/${symlink:1} $HOME/$symlink
-done < $links
+
+# Bash safety
+set -o errexit -o nounset -o pipefail
+
+# Links list file
+LINKS="${HOME}/dotfiles/install.list"
+
+# Check if list file exists
+[ ! -f "${LINKS}" ] && echo "Links list file not found. Exiting." && exit 1
+
+# Read files
+while read SYMLINK; do
+  # Check if file/symlink exist
+  [ -f "${HOME}/${SYMLINK}" ] && echo -e "File exists:\t${HOME}/${SYMLINK}" && continue
+  # Check if destination exists
+  [ ! -f "${HOME}/dotfiles/${SYMLINK:1}" ] && echo -e "Source missing:\t${HOME}/dotfiles/${SYMLINK:1}" && continue
+  # Symlink the dotfile
+  echo -e "Linking:\t${HOME}/dotfiles/${SYMLINK:1} -> ${HOME}/${SYMLINK}"
+  ln -s "${HOME}/dotfiles/${SYMLINK:1}" "${HOME}/${SYMLINK}"
+done < "${LINKS}"
